package com.sentinel.feature.logs

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.AssistChip
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.sentinel.core.model.AlertSeverity
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

data class EvidenceArchiveItemUi(
    val id: Long,
    val fileName: String,
    val absolutePath: String,
    val timestampEpochMs: Long,
    val severity: AlertSeverity,
    val forensicTimeline: String,
    val vibrationPeak: Double,
    val radarPeakCm: Int,
    val mobileLatitude: Double,
    val mobileLongitude: Double
)

@Composable
fun LogsScreen(
    archiveItems: List<EvidenceArchiveItemUi>,
    onViewPdf: (absolutePath: String) -> Unit
) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(12.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceContainerHigh)) {
            Column(modifier = Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Text(text = "Evidence Archive", style = MaterialTheme.typography.titleLarge)
                Text(
                    text = "Persistent forensic logs generated by the automated legal pipeline.",
                    style = MaterialTheme.typography.bodyMedium
                )
            }
        }

        LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp)) {
            items(archiveItems, key = { it.fileName }) { item ->
                ArchiveRow(item = item, onViewPdf = onViewPdf)
            }
        }
    }
}

@Composable
private fun ArchiveRow(
    item: EvidenceArchiveItemUi,
    onViewPdf: (absolutePath: String) -> Unit
) {
    val severityText = item.severity.name
    val time = SimpleDateFormat("dd MMM yyyy, hh:mm:ss a", Locale.US).format(Date(item.timestampEpochMs))

    Card(elevation = CardDefaults.cardElevation(defaultElevation = 4.dp)) {
        Column(modifier = Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                Text(
                    text = item.fileName,
                    style = MaterialTheme.typography.titleMedium,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis,
                    modifier = Modifier.weight(1f)
                )
                AssistChip(onClick = {}, label = { Text(severityText) })
            }
            Text(text = "Time: $time", style = MaterialTheme.typography.bodyMedium)
            Text(
                text = item.forensicTimeline,
                style = MaterialTheme.typography.bodyMedium,
                maxLines = 2,
                overflow = TextOverflow.Ellipsis
            )
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                Text(
                    text = "Vib ${"%.2f".format(item.vibrationPeak)}g",
                    style = MaterialTheme.typography.labelLarge
                )
                Text(
                    text = "Radar ${item.radarPeakCm}cm",
                    style = MaterialTheme.typography.labelLarge
                )
                Text(
                    text = "IR<100",
                    style = MaterialTheme.typography.labelLarge
                )
            }
            Text(
                text = "GPS ${"%.6f".format(item.mobileLatitude)}, ${"%.6f".format(item.mobileLongitude)}",
                style = MaterialTheme.typography.bodySmall,
                maxLines = 1,
                overflow = TextOverflow.Ellipsis
            )
            OutlinedButton(onClick = { onViewPdf(item.absolutePath) }) {
                Text("View Dossier")
            }
        }
    }
}
